### ISSUE TITLE
Default to using notified_ids=[]

### ISSUE THREAD

**Issue by mkdir-washington-edu** [judell/h_notify#2]
From: https://hypothesis.zendesk.com/agent/tickets/6010
Not entirely sure I have this right, so feel free to give me feedback:

User is trying to add Slack to the tools they're using, and wasn't adding "notified_ids=[]". You decided it should default to that.

Finally, you wrote:
"The error is just a traceback that's unnecessarily printed if namemap.json doesn't exist. But you should really try it, it's very cool to be able to @mention somebody's Slack name in an annotation and have them be tagged in Slack."

**Comment by judell** [comment]
> You decided it should default to that.

Done.
